version: '2'
volumes:
  unstructured_data:
  semistructured_data:
services:
  logstash:
    build: ./logstash
    volumes:
      -
    command: bin/logstash -f pipeline/logstash.conf
    depends_on:
      - elasticsearch
  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200
    command: bin/elasticsearch
