version: '2'
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - 9200:9200
    command: bin/elasticsearch
  kibana:
    build: ./kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  logstash:
    build: ./logstash
    command: bin/logstash -f pipeline/logstash.conf
    depends_on:
      - elasticsearch
