version: '2'
services:
  beats:
    build: ./beats
  elasticsearch:
    build: ./logstash
  kibana: ./kibana
    build: ./kibana
  logstash:
    build: ./logstash
    command: bin/logstash -f pipeline/logstash.conf

